### ISSUE TITLE
Sixkillers puppy spawn like crazy

### ISSUE THREAD

**Issue by nopresent4u** [manmaed/CutePuppyModIssues#4]
Im trying to set up a server on Curse with your mod, and the Sixkillers puppies spawn like crazy almost filling my screen with the boss health bar. I want to disable normal spawn due to this, is this doable? 1.10.2 version 1.1

**Comment by manmaed** [comment]
i will look into it

**Comment by DinnerBeef** [comment]
also a list of all the mods that are on the server would be nice

**Comment by manmaed** [comment]
So what i would like is a list of mods on the server(and or Packname on Curse), World Type (SuperFlat, Default, etc) and the seed if not i can make a config to disable the Sixkiller Puppy form spawning

**Comment by nopresent4u** [comment]
Hi, I will send this as soon as I get home after work. Amazing fast response 😊

I do not have a published pack yet, but I will send the whole list (all of them except Optifine is found on curse)
BTW the kids LOVE your mod, they are so happy with it!!!

Best regards

Rebecca Eriksson

Från: manmaed [mailto:notifications@github.com]
Skickat: den 1 juni 2017 00:20
Till: manmaed/CutePuppyModIssues <CutePuppyModIssues@noreply.github.com>
Kopia: nopresent4u <rebecca.eriksson@outlook.com>; Author <author@noreply.github.com>
Ämne: Re: [manmaed/CutePuppyModIssues] Sixkillers puppy spawn like crazy (#4)


So what i would like is a list of mods on the server(and or Packname on Curse), World Type (SuperFlat, Default, etc) and the seed if not i can make a config to disable the Sixkiller Puppy form spawning

**Comment by manmaed** [comment]
Ok so Verson 1.2 adds a config to stop spawns of sixkiller puppys

**Comment by manmaed** [comment]
have also lowerd spawn in 2.0 (not out yet)
